---
hostname: Dist-SW01
role: dist
site: DC

vlans: []

svis: []

l3_interfaces:
  - name: Gig0/0
    description: "To Core-SW01 (172.16.0.0/29)"
    ip: "172.16.0.3"
    mask: "255.255.255.248"
  - name: Gig0/1
    description: "To Core-SW02 (172.14.0.0/29)"
    ip: "172.14.0.2"
    mask: "255.255.255.248"

trunk_ports:
  - { name: "Gig1/0", native_vlan: 110, allowed_vlans: "110,120", description: "To Access-SW01" }
  - { name: "Gig1/1", native_vlan: 110, allowed_vlans: "110,120", description: "To Access-SW02" }

ospf:
  process_id: 20
  router_id: 2.2.2.3
  networks:
    - { network: "172.16.0.0", wildcard: "0.0.0.7", area: 0 }
    - { network: "172.14.0.0", wildcard: "0.0.0.7", area: 0 }
