---
hostname: Firewall-HQ
role: firewall
site: HQ

outside_interface: Gig0/0
inside_interface: Gig0/1

outside_ip: 203.0.113.10
outside_mask: 255.255.255.248
inside_ip: 11.1.1.1
inside_mask: 255.255.255.248
peer_ip: 198.51.100.10
